In [3]:
import copy  # not used
import os
import sys
import time

import pickle

import numpy as np
import pandas as pd

from src.toric_model import Toric_code
from src.planar_model import Planar_code
from src.mcmc import *
from decoders import *
from src.mwpm import *


# This function generates training data with help of the MCMC algorithm
def generate(file_path, params, max_capacity=10**4, nbr_datapoints=10**6, fixed_errors=None):

    if params['code'] == 'planar':
        nbr_eq_class = 4
    elif params['code'] == 'toric':
        nbr_eq_class = 16

    if params['method'] == "all":
        nbr_eq_class *= 3
    # Creates data file if there is none otherwise adds to it
    try:
        df = pd.read_pickle(file_path)
        nbr_existing_data = df.index[-1][0] + 1
    except:
        df = pd.DataFrame()
        nbr_existing_data = 0

    print('\nDataFrame with ' + str(nbr_existing_data) +
          ' datapoints opened at: ' + str(file_path))

    # Stop the file from exceeding the max limit of nbr of datapoints
    nbr_to_generate = min(max_capacity-nbr_existing_data, nbr_datapoints)
    if nbr_to_generate < nbr_datapoints:
        print('Generating ' + str(max(nbr_to_generate, 0))
              + ' datapoins instead of ' + str(nbr_datapoints)
              + ', as the given number would overflow existing file')

    if fixed_errors != None:
        nbr_to_generate = 10000000
    failed_syndroms = 0

    df_list = []  # Initiate temporary list

    # Loop to generate data points
    for i in range(nbr_existing_data, nbr_existing_data + nbr_to_generate):
        print('Starting generation of point nr: ' + str(i + 1))

        # Initiate code
        if params['code'] == 'toric':
            init_code = Toric_code(params['size'])
            init_code.generate_random_error(params['p_error'])
        elif params['code'] == 'planar':
            init_code = Planar_code(params['size'])
            #print(type(init_code))
            init_code.generate_random_error(params['p_error'])

        # Flatten initial qubit matrix to store in dataframe
        df_qubit = copy.deepcopy(init_code.qubit_matrix)
        eq_true = init_code.define_equivalence_class()
    
        vertex_defects = init_code.vertex_defects
        plaquette_defects = init_code.plaquette_defects
        
        
        vertex_defects = 1*vertex_defects
        plaquette_defects = 1*plaquette_defects
        #print(vertex_defects)
        #print(plaquette_defects)
        
        
        pickle_defects = open("defect_matrices/s9p1/dict.defects","ab")
        pickle.dump((vertex_defects,plaquette_defects),pickle_defects)
        pickle_defects.close()
        

        
        
        #vdefect_matrix_file.close()
        #pdefect_matrix_file.close()
        
    ###    
        if params['mwpm_init']: #get mwpm starting points
            #print()
            init_code = class_sorted_mwpm(init_code)
            print('Starting in MWPM state')
        else: #randomize input matrix, no trace of seed.
            init_code.qubit_matrix, _ = init_code.apply_random_logical()
            init_code.qubit_matrix = init_code.apply_stabilizers_uniform()
            print('Starting in random state')

        # Generate data for DataFrame storage  OBS now using full bincount, change this
        if params['method'] == "PTEQ":
            df_eq_distr = PTEQ(init_code, params['p_error'])
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        if params['method'] == "PTDC":
            df_eq_distr, conv = PTDC(init_code, params['p_error'], params['p_sampling'])
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        if params['method'] == "PTRC":
            df_eq_distr, conv = PTRC(init_code, params['p_error'], params['p_sampling'])
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        elif params['method'] == "STDC":
            df_eq_distr = STDC(init_code, params['p_error'], params['p_sampling'], steps=params['steps'], droplets=params['droplets'])
            df_eq_distr = np.array(df_eq_distr)
            #print(df_eq_distr)
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        elif params['method'] == "ST":
            df_eq_distr = single_temp(init_code, params['p_error'], params['steps'])
            df_eq_distr = np.array(df_eq_distr)
            if np.argmin(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        elif params['method'] == "STRC":
            df_eq_distr = STRC(init_code, params['p_error'], p_sampling=params['p_sampling'], steps=params['steps'], droplets=params['droplets'])
            df_eq_distr = np.array(df_eq_distr)
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        elif params['method'] == "all":
            #init_code.qubit_matrix = init_code.apply_stabilizers_uniform()
            #df_eq_distr1 = single_temp(init_code, params['p_error'],params['steps'])

            #init_code.qubit_matrix = init_code.apply_stabilizers_uniform()
            
            choice = regular_mwpm(copy.deepcopy(init_code))
            df_eq_distr1 = np.zeros((4)).astype(np.uint8)
            df_eq_distr1[choice] = 100
            
            #df_eq_distr2 = PTEQ(init_code, params['p_error'])

            #init_code.qubit_matrix = init_code.apply_stabilizers_uniform()
            df_eq_distr3 = STDC(init_code, params['p_error'], p_sampling=params['p_sampling'], steps=params['steps'], droplets=params['droplets'])

            df_eq_distr = np.concatenate((df_eq_distr1,df_eq_distr3), axis=0)
        elif params['method'] == "eMWPM":
            out = class_sorted_mwpm(copy.deepcopy(init_code))
            lens = np.zeros((4))
            for j in range(4):
                lens[j] = out[j].count_errors()
            choice = np.argmin(lens)
            df_eq_distr = np.zeros((4)).astype(np.uint8)
            df_eq_distr[choice] = 100
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1
        elif params['method'] == "MWPM":
            #print(type(init_code))
            choice = regular_mwpm(copy.deepcopy(init_code))
            #choice = regular_mwpm(init_code_pre_mwpm)
            
            df_eq_distr = np.zeros((4)).astype(np.uint8)
            df_eq_distr[choice] = 100
            if np.argmax(df_eq_distr) != eq_true:
                print('Failed syndrom, total now:', failed_syndroms)
                failed_syndroms += 1

        # Generate data for DataFrame storage  OBS now using full bincount, change this
        #print(df_eq_distr)
        # Create indices for generated data
        names = ['data_nr', 'type']
        index_qubit = pd.MultiIndex.from_product([[i], np.arange(1)],
                                                 names=names)
        index_distr = pd.MultiIndex.from_product([[i], np.arange(1)+1], names=names)
    
        # Add data to Dataframes
        df_qubit = pd.DataFrame([[df_qubit.astype(np.uint8)]], index=index_qubit,
                                columns=['data'])
        df_distr = pd.DataFrame([[df_eq_distr]],
                                index=index_distr, columns=['data'])
        
        # Add dataframes to temporary list to shorten computation time

        
        ####
        pickle_eq_dist = open("defect_matrices/s9p1/dict.eq_distr","ab")
        pickle.dump(df_eq_distr,pickle_eq_dist)
        pickle_eq_dist.close()
        #####
        df_list.append(df_qubit)
        df_list.append(df_distr)
        
        # Every x iteration adds data to data file from temporary list
        # and clears temporary list

        if (i + 1) % 10000 == 0: # this needs to be sufficiently big that rsync has time to sync files before update, maybe change this to be time-based instead.
            df = df.append(df_list)
            df_list.clear()
            print('Intermediate save point reached (writing over)')
            df.to_pickle(file_path)
            print('Failed so far:', failed_syndroms)

        # If the desired amount of errors have been achieved, break the loop and finish up
        if failed_syndroms == fixed_errors:
            print('Desired amount of failes syndroms achieved, breaking loop.')
            break

    # Adds any remaining data from temporary list to data file when run is over
    if len(df_list) > 0:
        df = df.append(df_list)
        print('\nSaving all generated data (writing over)')
        df.to_pickle(file_path)

    print('\nCompleted')


if __name__ == '__main__':
    # Get job array id, working directory
    #try:
#        array_id = os.getenv('SLURM_ARRAY_TASK_ID')
#        local_dir = os.getenv('TMPDIR')
#    except:
    array_id = '10'
    local_dir = './data'
    print('Invalid environment variables, using array_id 0 and local dir.')

    params = {'code': "planar",
            'method': "STDC",
            'size': 9,
            'p_error': 0.1,#np.round((0.05 + float(array_id) / 50), decimals=2),
            'p_sampling': 0.1,#np.round((0.05 + float(array_id) / 50), decimals=2),
            'droplets':1,
            'mwpm_init':True,
            'fixed_errors':None,
            'Nc':None,
            'iters': 10,
            'conv_criteria':'error_based',
            'SEQ': 2,
            'TOPS': 10,
            'eps': 0.1}
    # Steps is a function of code size L
    params.update({'steps': int(params['size'] ** 4)})

    print('Nbr of steps to take if applicable:', params['steps'])

    # Build file path
    file_path = os.path.join(local_dir, 'data_size_'+str(params['size'])+'_method_'+params['method']+'_id_' + array_id + '_perror_' + str(params['p_error']) + '.xz')

    # Generate data
    generate(file_path, params, nbr_datapoints=5000, fixed_errors=params['fixed_errors'])

    # View data file

    '''iterator = MCMCDataReader(file_path, params['size'])
    data = iterator.full()
    for k in range(int(len(data)/2)):
        qubit_matrix = data[2*k].reshape(2,params['size'],params['size'])
        eq_distr = data[2*k+1]

        print(qubit_matrix)
        print(eq_distr)'''


Invalid environment variables, using array_id 0 and local dir.
Nbr of steps to take if applicable: 6561

DataFrame with 0 datapoints opened at: ./data/data_size_9_method_STDC_id_10_perror_0.1.xz
Starting generation of point nr: 1
Starting in MWPM state
Starting generation of point nr: 2
Starting in MWPM state
Starting generation of point nr: 3
Starting in MWPM state
Starting generation of point nr: 4
Starting in MWPM state
Starting generation of point nr: 5
Starting in MWPM state
Starting generation of point nr: 6
Starting in MWPM state
Starting generation of point nr: 7
Starting in MWPM state
Starting generation of point nr: 8
Starting in MWPM state
Starting generation of point nr: 9
Starting in MWPM state
Starting generation of point nr: 10
Starting in MWPM state
Starting generation of point nr: 11
Starting in MWPM state
Starting generation of point nr: 12
Starting in MWPM state
Starting generation of point nr: 13
Starting in MWPM state
Starting generation of point nr: 14
Starting in

Starting generation of point nr: 135
Starting in MWPM state
Starting generation of point nr: 136
Starting in MWPM state
Starting generation of point nr: 137
Starting in MWPM state
Starting generation of point nr: 138
Starting in MWPM state
Starting generation of point nr: 139
Starting in MWPM state
Starting generation of point nr: 140
Starting in MWPM state
Starting generation of point nr: 141
Starting in MWPM state
Starting generation of point nr: 142
Starting in MWPM state
Starting generation of point nr: 143
Starting in MWPM state
Starting generation of point nr: 144
Starting in MWPM state
Starting generation of point nr: 145
Starting in MWPM state
Starting generation of point nr: 146
Starting in MWPM state
Starting generation of point nr: 147
Starting in MWPM state
Starting generation of point nr: 148
Starting in MWPM state
Starting generation of point nr: 149
Starting in MWPM state
Starting generation of point nr: 150
Starting in MWPM state
Starting generation of point nr: 151
Sta

Starting generation of point nr: 273
Starting in MWPM state
Starting generation of point nr: 274
Starting in MWPM state
Starting generation of point nr: 275
Starting in MWPM state
Starting generation of point nr: 276
Starting in MWPM state
Starting generation of point nr: 277
Starting in MWPM state
Starting generation of point nr: 278
Starting in MWPM state
Starting generation of point nr: 279
Starting in MWPM state
Starting generation of point nr: 280
Starting in MWPM state
Starting generation of point nr: 281
Starting in MWPM state
Starting generation of point nr: 282
Starting in MWPM state
Starting generation of point nr: 283
Starting in MWPM state
Starting generation of point nr: 284
Starting in MWPM state
Starting generation of point nr: 285
Starting in MWPM state
Starting generation of point nr: 286
Starting in MWPM state
Starting generation of point nr: 287
Starting in MWPM state
Starting generation of point nr: 288
Starting in MWPM state
Starting generation of point nr: 289
Sta

Starting generation of point nr: 409
Starting in MWPM state
Starting generation of point nr: 410
Starting in MWPM state
Starting generation of point nr: 411
Starting in MWPM state
Starting generation of point nr: 412
Starting in MWPM state
Starting generation of point nr: 413
Starting in MWPM state
Starting generation of point nr: 414
Starting in MWPM state
Starting generation of point nr: 415
Starting in MWPM state
Starting generation of point nr: 416
Starting in MWPM state
Failed syndrom, total now: 5
Starting generation of point nr: 417
Starting in MWPM state
Starting generation of point nr: 418
Starting in MWPM state
Starting generation of point nr: 419
Starting in MWPM state
Starting generation of point nr: 420
Starting in MWPM state
Starting generation of point nr: 421
Starting in MWPM state
Starting generation of point nr: 422
Starting in MWPM state
Starting generation of point nr: 423
Starting in MWPM state
Starting generation of point nr: 424
Starting in MWPM state
Starting ge

Failed syndrom, total now: 8
Starting generation of point nr: 545
Starting in MWPM state
Starting generation of point nr: 546
Starting in MWPM state
Starting generation of point nr: 547
Starting in MWPM state
Starting generation of point nr: 548
Starting in MWPM state
Starting generation of point nr: 549
Starting in MWPM state
Starting generation of point nr: 550
Starting in MWPM state
Starting generation of point nr: 551
Starting in MWPM state
Starting generation of point nr: 552
Starting in MWPM state
Starting generation of point nr: 553
Starting in MWPM state
Starting generation of point nr: 554
Starting in MWPM state
Starting generation of point nr: 555
Starting in MWPM state
Starting generation of point nr: 556
Starting in MWPM state
Starting generation of point nr: 557
Starting in MWPM state
Starting generation of point nr: 558
Starting in MWPM state
Starting generation of point nr: 559
Starting in MWPM state
Starting generation of point nr: 560
Starting in MWPM state
Starting ge

Starting generation of point nr: 681
Starting in MWPM state
Starting generation of point nr: 682
Starting in MWPM state
Failed syndrom, total now: 11
Starting generation of point nr: 683
Starting in MWPM state
Starting generation of point nr: 684
Starting in MWPM state
Starting generation of point nr: 685
Starting in MWPM state
Starting generation of point nr: 686
Starting in MWPM state
Failed syndrom, total now: 12
Starting generation of point nr: 687
Starting in MWPM state
Starting generation of point nr: 688
Starting in MWPM state
Starting generation of point nr: 689
Starting in MWPM state
Starting generation of point nr: 690
Starting in MWPM state
Starting generation of point nr: 691
Starting in MWPM state
Starting generation of point nr: 692
Starting in MWPM state
Starting generation of point nr: 693
Starting in MWPM state
Starting generation of point nr: 694
Starting in MWPM state
Starting generation of point nr: 695
Starting in MWPM state
Starting generation of point nr: 696
Sta

Starting generation of point nr: 816
Starting in MWPM state
Starting generation of point nr: 817
Starting in MWPM state
Starting generation of point nr: 818
Starting in MWPM state
Starting generation of point nr: 819
Starting in MWPM state
Starting generation of point nr: 820
Starting in MWPM state
Starting generation of point nr: 821
Starting in MWPM state
Starting generation of point nr: 822
Starting in MWPM state
Starting generation of point nr: 823
Starting in MWPM state
Starting generation of point nr: 824
Starting in MWPM state
Starting generation of point nr: 825
Starting in MWPM state
Starting generation of point nr: 826
Starting in MWPM state
Starting generation of point nr: 827
Starting in MWPM state
Starting generation of point nr: 828
Starting in MWPM state
Starting generation of point nr: 829
Starting in MWPM state
Starting generation of point nr: 830
Starting in MWPM state
Starting generation of point nr: 831
Starting in MWPM state
Starting generation of point nr: 832
Sta

Starting generation of point nr: 952
Starting in MWPM state
Starting generation of point nr: 953
Starting in MWPM state
Starting generation of point nr: 954
Starting in MWPM state
Starting generation of point nr: 955
Starting in MWPM state
Starting generation of point nr: 956
Starting in MWPM state
Starting generation of point nr: 957
Starting in MWPM state
Starting generation of point nr: 958
Starting in MWPM state
Starting generation of point nr: 959
Starting in MWPM state
Starting generation of point nr: 960
Starting in MWPM state
Starting generation of point nr: 961
Starting in MWPM state
Starting generation of point nr: 962
Starting in MWPM state
Starting generation of point nr: 963
Starting in MWPM state
Starting generation of point nr: 964
Starting in MWPM state
Starting generation of point nr: 965
Starting in MWPM state
Starting generation of point nr: 966
Starting in MWPM state
Starting generation of point nr: 967
Starting in MWPM state
Starting generation of point nr: 968
Sta

Starting generation of point nr: 1088
Starting in MWPM state
Starting generation of point nr: 1089
Starting in MWPM state
Starting generation of point nr: 1090
Starting in MWPM state
Starting generation of point nr: 1091
Starting in MWPM state
Starting generation of point nr: 1092
Starting in MWPM state
Starting generation of point nr: 1093
Starting in MWPM state
Starting generation of point nr: 1094
Starting in MWPM state
Starting generation of point nr: 1095
Starting in MWPM state
Starting generation of point nr: 1096
Starting in MWPM state
Starting generation of point nr: 1097
Starting in MWPM state
Starting generation of point nr: 1098
Starting in MWPM state
Starting generation of point nr: 1099
Starting in MWPM state
Starting generation of point nr: 1100
Starting in MWPM state
Starting generation of point nr: 1101
Starting in MWPM state
Starting generation of point nr: 1102
Starting in MWPM state
Starting generation of point nr: 1103
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1224
Starting in MWPM state
Starting generation of point nr: 1225
Starting in MWPM state
Starting generation of point nr: 1226
Starting in MWPM state
Starting generation of point nr: 1227
Starting in MWPM state
Starting generation of point nr: 1228
Starting in MWPM state
Starting generation of point nr: 1229
Starting in MWPM state
Starting generation of point nr: 1230
Starting in MWPM state
Starting generation of point nr: 1231
Starting in MWPM state
Starting generation of point nr: 1232
Starting in MWPM state
Starting generation of point nr: 1233
Starting in MWPM state
Starting generation of point nr: 1234
Starting in MWPM state
Starting generation of point nr: 1235
Starting in MWPM state
Starting generation of point nr: 1236
Starting in MWPM state
Starting generation of point nr: 1237
Starting in MWPM state
Starting generation of point nr: 1238
Starting in MWPM state
Starting generation of point nr: 1239
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1358
Starting in MWPM state
Starting generation of point nr: 1359
Starting in MWPM state
Starting generation of point nr: 1360
Starting in MWPM state
Starting generation of point nr: 1361
Starting in MWPM state
Starting generation of point nr: 1362
Starting in MWPM state
Starting generation of point nr: 1363
Starting in MWPM state
Starting generation of point nr: 1364
Starting in MWPM state
Starting generation of point nr: 1365
Starting in MWPM state
Starting generation of point nr: 1366
Starting in MWPM state
Starting generation of point nr: 1367
Starting in MWPM state
Starting generation of point nr: 1368
Starting in MWPM state
Starting generation of point nr: 1369
Starting in MWPM state
Starting generation of point nr: 1370
Starting in MWPM state
Starting generation of point nr: 1371
Starting in MWPM state
Starting generation of point nr: 1372
Starting in MWPM state
Starting generation of point nr: 1373
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1494
Starting in MWPM state
Starting generation of point nr: 1495
Starting in MWPM state
Starting generation of point nr: 1496
Starting in MWPM state
Starting generation of point nr: 1497
Starting in MWPM state
Starting generation of point nr: 1498
Starting in MWPM state
Starting generation of point nr: 1499
Starting in MWPM state
Starting generation of point nr: 1500
Starting in MWPM state
Starting generation of point nr: 1501
Starting in MWPM state
Starting generation of point nr: 1502
Starting in MWPM state
Starting generation of point nr: 1503
Starting in MWPM state
Starting generation of point nr: 1504
Starting in MWPM state
Starting generation of point nr: 1505
Starting in MWPM state
Starting generation of point nr: 1506
Starting in MWPM state
Starting generation of point nr: 1507
Starting in MWPM state
Starting generation of point nr: 1508
Starting in MWPM state
Starting generation of point nr: 1509
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1629
Starting in MWPM state
Starting generation of point nr: 1630
Starting in MWPM state
Starting generation of point nr: 1631
Starting in MWPM state
Starting generation of point nr: 1632
Starting in MWPM state
Starting generation of point nr: 1633
Starting in MWPM state
Starting generation of point nr: 1634
Starting in MWPM state
Starting generation of point nr: 1635
Starting in MWPM state
Starting generation of point nr: 1636
Starting in MWPM state
Starting generation of point nr: 1637
Starting in MWPM state
Starting generation of point nr: 1638
Starting in MWPM state
Starting generation of point nr: 1639
Starting in MWPM state
Starting generation of point nr: 1640
Starting in MWPM state
Starting generation of point nr: 1641
Starting in MWPM state
Starting generation of point nr: 1642
Starting in MWPM state
Starting generation of point nr: 1643
Starting in MWPM state
Starting generation of point nr: 1644
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1763
Starting in MWPM state
Starting generation of point nr: 1764
Starting in MWPM state
Starting generation of point nr: 1765
Starting in MWPM state
Starting generation of point nr: 1766
Starting in MWPM state
Starting generation of point nr: 1767
Starting in MWPM state
Starting generation of point nr: 1768
Starting in MWPM state
Starting generation of point nr: 1769
Starting in MWPM state
Starting generation of point nr: 1770
Starting in MWPM state
Starting generation of point nr: 1771
Starting in MWPM state
Starting generation of point nr: 1772
Starting in MWPM state
Starting generation of point nr: 1773
Starting in MWPM state
Starting generation of point nr: 1774
Starting in MWPM state
Starting generation of point nr: 1775
Starting in MWPM state
Starting generation of point nr: 1776
Starting in MWPM state
Starting generation of point nr: 1777
Starting in MWPM state
Starting generation of point nr: 1778
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 1897
Starting in MWPM state
Starting generation of point nr: 1898
Starting in MWPM state
Failed syndrom, total now: 33
Starting generation of point nr: 1899
Starting in MWPM state
Starting generation of point nr: 1900
Starting in MWPM state
Starting generation of point nr: 1901
Starting in MWPM state
Starting generation of point nr: 1902
Starting in MWPM state
Starting generation of point nr: 1903
Starting in MWPM state
Starting generation of point nr: 1904
Starting in MWPM state
Starting generation of point nr: 1905
Starting in MWPM state
Failed syndrom, total now: 34
Starting generation of point nr: 1906
Starting in MWPM state
Starting generation of point nr: 1907
Starting in MWPM state
Starting generation of point nr: 1908
Starting in MWPM state
Starting generation of point nr: 1909
Starting in MWPM state
Starting generation of point nr: 1910
Starting in MWPM state
Starting generation of point nr: 1911
Starting in MWPM state
Starting generation of po

Starting generation of point nr: 2031
Starting in MWPM state
Starting generation of point nr: 2032
Starting in MWPM state
Starting generation of point nr: 2033
Starting in MWPM state
Starting generation of point nr: 2034
Starting in MWPM state
Starting generation of point nr: 2035
Starting in MWPM state
Starting generation of point nr: 2036
Starting in MWPM state
Starting generation of point nr: 2037
Starting in MWPM state
Starting generation of point nr: 2038
Starting in MWPM state
Starting generation of point nr: 2039
Starting in MWPM state
Starting generation of point nr: 2040
Starting in MWPM state
Starting generation of point nr: 2041
Starting in MWPM state
Starting generation of point nr: 2042
Starting in MWPM state
Starting generation of point nr: 2043
Starting in MWPM state
Starting generation of point nr: 2044
Starting in MWPM state
Starting generation of point nr: 2045
Starting in MWPM state
Starting generation of point nr: 2046
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2165
Starting in MWPM state
Starting generation of point nr: 2166
Starting in MWPM state
Starting generation of point nr: 2167
Starting in MWPM state
Starting generation of point nr: 2168
Starting in MWPM state
Starting generation of point nr: 2169
Starting in MWPM state
Starting generation of point nr: 2170
Starting in MWPM state
Starting generation of point nr: 2171
Starting in MWPM state
Starting generation of point nr: 2172
Starting in MWPM state
Starting generation of point nr: 2173
Starting in MWPM state
Starting generation of point nr: 2174
Starting in MWPM state
Starting generation of point nr: 2175
Starting in MWPM state
Starting generation of point nr: 2176
Starting in MWPM state
Starting generation of point nr: 2177
Starting in MWPM state
Starting generation of point nr: 2178
Starting in MWPM state
Starting generation of point nr: 2179
Starting in MWPM state
Starting generation of point nr: 2180
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2299
Starting in MWPM state
Starting generation of point nr: 2300
Starting in MWPM state
Starting generation of point nr: 2301
Starting in MWPM state
Starting generation of point nr: 2302
Starting in MWPM state
Starting generation of point nr: 2303
Starting in MWPM state
Starting generation of point nr: 2304
Starting in MWPM state
Starting generation of point nr: 2305
Starting in MWPM state
Starting generation of point nr: 2306
Starting in MWPM state
Starting generation of point nr: 2307
Starting in MWPM state
Starting generation of point nr: 2308
Starting in MWPM state
Starting generation of point nr: 2309
Starting in MWPM state
Starting generation of point nr: 2310
Starting in MWPM state
Starting generation of point nr: 2311
Starting in MWPM state
Starting generation of point nr: 2312
Starting in MWPM state
Starting generation of point nr: 2313
Starting in MWPM state
Starting generation of point nr: 2314
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2433
Starting in MWPM state
Starting generation of point nr: 2434
Starting in MWPM state
Starting generation of point nr: 2435
Starting in MWPM state
Starting generation of point nr: 2436
Starting in MWPM state
Starting generation of point nr: 2437
Starting in MWPM state
Starting generation of point nr: 2438
Starting in MWPM state
Starting generation of point nr: 2439
Starting in MWPM state
Starting generation of point nr: 2440
Starting in MWPM state
Starting generation of point nr: 2441
Starting in MWPM state
Starting generation of point nr: 2442
Starting in MWPM state
Starting generation of point nr: 2443
Starting in MWPM state
Starting generation of point nr: 2444
Starting in MWPM state
Starting generation of point nr: 2445
Starting in MWPM state
Starting generation of point nr: 2446
Starting in MWPM state
Starting generation of point nr: 2447
Starting in MWPM state
Starting generation of point nr: 2448
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2567
Starting in MWPM state
Starting generation of point nr: 2568
Starting in MWPM state
Starting generation of point nr: 2569
Starting in MWPM state
Starting generation of point nr: 2570
Starting in MWPM state
Starting generation of point nr: 2571
Starting in MWPM state
Starting generation of point nr: 2572
Starting in MWPM state
Starting generation of point nr: 2573
Starting in MWPM state
Starting generation of point nr: 2574
Starting in MWPM state
Starting generation of point nr: 2575
Starting in MWPM state
Starting generation of point nr: 2576
Starting in MWPM state
Starting generation of point nr: 2577
Starting in MWPM state
Starting generation of point nr: 2578
Starting in MWPM state
Starting generation of point nr: 2579
Starting in MWPM state
Starting generation of point nr: 2580
Starting in MWPM state
Starting generation of point nr: 2581
Starting in MWPM state
Starting generation of point nr: 2582
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2700
Starting in MWPM state
Starting generation of point nr: 2701
Starting in MWPM state
Starting generation of point nr: 2702
Starting in MWPM state
Starting generation of point nr: 2703
Starting in MWPM state
Starting generation of point nr: 2704
Starting in MWPM state
Starting generation of point nr: 2705
Starting in MWPM state
Starting generation of point nr: 2706
Starting in MWPM state
Starting generation of point nr: 2707
Starting in MWPM state
Starting generation of point nr: 2708
Starting in MWPM state
Starting generation of point nr: 2709
Starting in MWPM state
Starting generation of point nr: 2710
Starting in MWPM state
Starting generation of point nr: 2711
Starting in MWPM state
Starting generation of point nr: 2712
Starting in MWPM state
Starting generation of point nr: 2713
Starting in MWPM state
Starting generation of point nr: 2714
Starting in MWPM state
Starting generation of point nr: 2715
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2836
Starting in MWPM state
Starting generation of point nr: 2837
Starting in MWPM state
Starting generation of point nr: 2838
Starting in MWPM state
Starting generation of point nr: 2839
Starting in MWPM state
Starting generation of point nr: 2840
Starting in MWPM state
Starting generation of point nr: 2841
Starting in MWPM state
Starting generation of point nr: 2842
Starting in MWPM state
Starting generation of point nr: 2843
Starting in MWPM state
Starting generation of point nr: 2844
Starting in MWPM state
Starting generation of point nr: 2845
Starting in MWPM state
Starting generation of point nr: 2846
Starting in MWPM state
Starting generation of point nr: 2847
Starting in MWPM state
Starting generation of point nr: 2848
Starting in MWPM state
Starting generation of point nr: 2849
Starting in MWPM state
Starting generation of point nr: 2850
Starting in MWPM state
Starting generation of point nr: 2851
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 2970
Starting in MWPM state
Starting generation of point nr: 2971
Starting in MWPM state
Starting generation of point nr: 2972
Starting in MWPM state
Starting generation of point nr: 2973
Starting in MWPM state
Starting generation of point nr: 2974
Starting in MWPM state
Starting generation of point nr: 2975
Starting in MWPM state
Starting generation of point nr: 2976
Starting in MWPM state
Starting generation of point nr: 2977
Starting in MWPM state
Starting generation of point nr: 2978
Starting in MWPM state
Starting generation of point nr: 2979
Starting in MWPM state
Starting generation of point nr: 2980
Starting in MWPM state
Starting generation of point nr: 2981
Starting in MWPM state
Starting generation of point nr: 2982
Starting in MWPM state
Starting generation of point nr: 2983
Starting in MWPM state
Starting generation of point nr: 2984
Starting in MWPM state
Starting generation of point nr: 2985
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 3104
Starting in MWPM state
Starting generation of point nr: 3105
Starting in MWPM state
Starting generation of point nr: 3106
Starting in MWPM state
Starting generation of point nr: 3107
Starting in MWPM state
Starting generation of point nr: 3108
Starting in MWPM state
Starting generation of point nr: 3109
Starting in MWPM state
Starting generation of point nr: 3110
Starting in MWPM state
Starting generation of point nr: 3111
Starting in MWPM state
Starting generation of point nr: 3112
Starting in MWPM state
Starting generation of point nr: 3113
Starting in MWPM state
Starting generation of point nr: 3114
Starting in MWPM state
Starting generation of point nr: 3115
Starting in MWPM state
Starting generation of point nr: 3116
Starting in MWPM state
Starting generation of point nr: 3117
Starting in MWPM state
Starting generation of point nr: 3118
Starting in MWPM state
Starting generation of point nr: 3119
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 3238
Starting in MWPM state
Starting generation of point nr: 3239
Starting in MWPM state
Starting generation of point nr: 3240
Starting in MWPM state
Starting generation of point nr: 3241
Starting in MWPM state
Starting generation of point nr: 3242
Starting in MWPM state
Starting generation of point nr: 3243
Starting in MWPM state
Starting generation of point nr: 3244
Starting in MWPM state
Starting generation of point nr: 3245
Starting in MWPM state
Starting generation of point nr: 3246
Starting in MWPM state
Starting generation of point nr: 3247
Starting in MWPM state
Starting generation of point nr: 3248
Starting in MWPM state
Starting generation of point nr: 3249
Starting in MWPM state
Starting generation of point nr: 3250
Starting in MWPM state
Starting generation of point nr: 3251
Starting in MWPM state
Starting generation of point nr: 3252
Starting in MWPM state
Starting generation of point nr: 3253
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 3370
Starting in MWPM state
Starting generation of point nr: 3371
Starting in MWPM state
Starting generation of point nr: 3372
Starting in MWPM state
Starting generation of point nr: 3373
Starting in MWPM state
Starting generation of point nr: 3374
Starting in MWPM state
Starting generation of point nr: 3375
Starting in MWPM state
Starting generation of point nr: 3376
Starting in MWPM state
Starting generation of point nr: 3377
Starting in MWPM state
Starting generation of point nr: 3378
Starting in MWPM state
Starting generation of point nr: 3379
Starting in MWPM state
Starting generation of point nr: 3380
Starting in MWPM state
Starting generation of point nr: 3381
Starting in MWPM state
Starting generation of point nr: 3382
Starting in MWPM state
Starting generation of point nr: 3383
Starting in MWPM state
Starting generation of point nr: 3384
Starting in MWPM state
Starting generation of point nr: 3385
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 3504
Starting in MWPM state
Starting generation of point nr: 3505
Starting in MWPM state
Starting generation of point nr: 3506
Starting in MWPM state
Starting generation of point nr: 3507
Starting in MWPM state
Starting generation of point nr: 3508
Starting in MWPM state
Starting generation of point nr: 3509
Starting in MWPM state
Starting generation of point nr: 3510
Starting in MWPM state
Starting generation of point nr: 3511
Starting in MWPM state
Failed syndrom, total now: 58
Starting generation of point nr: 3512
Starting in MWPM state
Starting generation of point nr: 3513
Starting in MWPM state
Starting generation of point nr: 3514
Starting in MWPM state
Starting generation of point nr: 3515
Starting in MWPM state
Starting generation of point nr: 3516
Starting in MWPM state
Starting generation of point nr: 3517
Starting in MWPM state
Starting generation of point nr: 3518
Starting in MWPM state
Starting generation of point nr: 3519
Starting in MWPM 

Starting generation of point nr: 3638
Starting in MWPM state
Starting generation of point nr: 3639
Starting in MWPM state
Starting generation of point nr: 3640
Starting in MWPM state
Starting generation of point nr: 3641
Starting in MWPM state
Starting generation of point nr: 3642
Starting in MWPM state
Starting generation of point nr: 3643
Starting in MWPM state
Starting generation of point nr: 3644
Starting in MWPM state
Starting generation of point nr: 3645
Starting in MWPM state
Starting generation of point nr: 3646
Starting in MWPM state
Starting generation of point nr: 3647
Starting in MWPM state
Starting generation of point nr: 3648
Starting in MWPM state
Starting generation of point nr: 3649
Starting in MWPM state
Starting generation of point nr: 3650
Starting in MWPM state
Starting generation of point nr: 3651
Starting in MWPM state
Starting generation of point nr: 3652
Starting in MWPM state
Starting generation of point nr: 3653
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 3772
Starting in MWPM state
Starting generation of point nr: 3773
Starting in MWPM state
Starting generation of point nr: 3774
Starting in MWPM state
Starting generation of point nr: 3775
Starting in MWPM state
Starting generation of point nr: 3776
Starting in MWPM state
Starting generation of point nr: 3777
Starting in MWPM state
Starting generation of point nr: 3778
Starting in MWPM state
Failed syndrom, total now: 64
Starting generation of point nr: 3779
Starting in MWPM state
Starting generation of point nr: 3780
Starting in MWPM state
Starting generation of point nr: 3781
Starting in MWPM state
Starting generation of point nr: 3782
Starting in MWPM state
Starting generation of point nr: 3783
Starting in MWPM state
Starting generation of point nr: 3784
Starting in MWPM state
Starting generation of point nr: 3785
Starting in MWPM state
Starting generation of point nr: 3786
Starting in MWPM state
Starting generation of point nr: 3787
Starting in MWPM 

Starting generation of point nr: 3906
Starting in MWPM state
Starting generation of point nr: 3907
Starting in MWPM state
Starting generation of point nr: 3908
Starting in MWPM state
Starting generation of point nr: 3909
Starting in MWPM state
Starting generation of point nr: 3910
Starting in MWPM state
Starting generation of point nr: 3911
Starting in MWPM state
Starting generation of point nr: 3912
Starting in MWPM state
Starting generation of point nr: 3913
Starting in MWPM state
Starting generation of point nr: 3914
Starting in MWPM state
Starting generation of point nr: 3915
Starting in MWPM state
Starting generation of point nr: 3916
Starting in MWPM state
Starting generation of point nr: 3917
Starting in MWPM state
Starting generation of point nr: 3918
Starting in MWPM state
Starting generation of point nr: 3919
Starting in MWPM state
Starting generation of point nr: 3920
Starting in MWPM state
Starting generation of point nr: 3921
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4039
Starting in MWPM state
Starting generation of point nr: 4040
Starting in MWPM state
Starting generation of point nr: 4041
Starting in MWPM state
Starting generation of point nr: 4042
Starting in MWPM state
Starting generation of point nr: 4043
Starting in MWPM state
Starting generation of point nr: 4044
Starting in MWPM state
Starting generation of point nr: 4045
Starting in MWPM state
Starting generation of point nr: 4046
Starting in MWPM state
Starting generation of point nr: 4047
Starting in MWPM state
Starting generation of point nr: 4048
Starting in MWPM state
Starting generation of point nr: 4049
Starting in MWPM state
Starting generation of point nr: 4050
Starting in MWPM state
Starting generation of point nr: 4051
Starting in MWPM state
Starting generation of point nr: 4052
Starting in MWPM state
Starting generation of point nr: 4053
Starting in MWPM state
Starting generation of point nr: 4054
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4173
Starting in MWPM state
Starting generation of point nr: 4174
Starting in MWPM state
Starting generation of point nr: 4175
Starting in MWPM state
Starting generation of point nr: 4176
Starting in MWPM state
Starting generation of point nr: 4177
Starting in MWPM state
Starting generation of point nr: 4178
Starting in MWPM state
Starting generation of point nr: 4179
Starting in MWPM state
Starting generation of point nr: 4180
Starting in MWPM state
Starting generation of point nr: 4181
Starting in MWPM state
Starting generation of point nr: 4182
Starting in MWPM state
Starting generation of point nr: 4183
Starting in MWPM state
Starting generation of point nr: 4184
Starting in MWPM state
Starting generation of point nr: 4185
Starting in MWPM state
Starting generation of point nr: 4186
Starting in MWPM state
Starting generation of point nr: 4187
Starting in MWPM state
Starting generation of point nr: 4188
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4307
Starting in MWPM state
Starting generation of point nr: 4308
Starting in MWPM state
Starting generation of point nr: 4309
Starting in MWPM state
Starting generation of point nr: 4310
Starting in MWPM state
Starting generation of point nr: 4311
Starting in MWPM state
Starting generation of point nr: 4312
Starting in MWPM state
Starting generation of point nr: 4313
Starting in MWPM state
Starting generation of point nr: 4314
Starting in MWPM state
Failed syndrom, total now: 75
Starting generation of point nr: 4315
Starting in MWPM state
Starting generation of point nr: 4316
Starting in MWPM state
Starting generation of point nr: 4317
Starting in MWPM state
Starting generation of point nr: 4318
Starting in MWPM state
Starting generation of point nr: 4319
Starting in MWPM state
Starting generation of point nr: 4320
Starting in MWPM state
Failed syndrom, total now: 76
Starting generation of point nr: 4321
Starting in MWPM state
Starting generation of po

Starting generation of point nr: 4439
Starting in MWPM state
Starting generation of point nr: 4440
Starting in MWPM state
Starting generation of point nr: 4441
Starting in MWPM state
Starting generation of point nr: 4442
Starting in MWPM state
Starting generation of point nr: 4443
Starting in MWPM state
Starting generation of point nr: 4444
Starting in MWPM state
Starting generation of point nr: 4445
Starting in MWPM state
Starting generation of point nr: 4446
Starting in MWPM state
Starting generation of point nr: 4447
Starting in MWPM state
Starting generation of point nr: 4448
Starting in MWPM state
Starting generation of point nr: 4449
Starting in MWPM state
Starting generation of point nr: 4450
Starting in MWPM state
Starting generation of point nr: 4451
Starting in MWPM state
Starting generation of point nr: 4452
Starting in MWPM state
Starting generation of point nr: 4453
Starting in MWPM state
Starting generation of point nr: 4454
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4573
Starting in MWPM state
Starting generation of point nr: 4574
Starting in MWPM state
Starting generation of point nr: 4575
Starting in MWPM state
Starting generation of point nr: 4576
Starting in MWPM state
Starting generation of point nr: 4577
Starting in MWPM state
Starting generation of point nr: 4578
Starting in MWPM state
Starting generation of point nr: 4579
Starting in MWPM state
Starting generation of point nr: 4580
Starting in MWPM state
Starting generation of point nr: 4581
Starting in MWPM state
Starting generation of point nr: 4582
Starting in MWPM state
Starting generation of point nr: 4583
Starting in MWPM state
Starting generation of point nr: 4584
Starting in MWPM state
Starting generation of point nr: 4585
Starting in MWPM state
Starting generation of point nr: 4586
Starting in MWPM state
Starting generation of point nr: 4587
Starting in MWPM state
Starting generation of point nr: 4588
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4707
Starting in MWPM state
Starting generation of point nr: 4708
Starting in MWPM state
Starting generation of point nr: 4709
Starting in MWPM state
Starting generation of point nr: 4710
Starting in MWPM state
Starting generation of point nr: 4711
Starting in MWPM state
Starting generation of point nr: 4712
Starting in MWPM state
Starting generation of point nr: 4713
Starting in MWPM state
Failed syndrom, total now: 85
Starting generation of point nr: 4714
Starting in MWPM state
Starting generation of point nr: 4715
Starting in MWPM state
Starting generation of point nr: 4716
Starting in MWPM state
Starting generation of point nr: 4717
Starting in MWPM state
Starting generation of point nr: 4718
Starting in MWPM state
Starting generation of point nr: 4719
Starting in MWPM state
Starting generation of point nr: 4720
Starting in MWPM state
Starting generation of point nr: 4721
Starting in MWPM state
Starting generation of point nr: 4722
Starting in MWPM 

Starting generation of point nr: 4841
Starting in MWPM state
Starting generation of point nr: 4842
Starting in MWPM state
Starting generation of point nr: 4843
Starting in MWPM state
Starting generation of point nr: 4844
Starting in MWPM state
Starting generation of point nr: 4845
Starting in MWPM state
Starting generation of point nr: 4846
Starting in MWPM state
Starting generation of point nr: 4847
Starting in MWPM state
Starting generation of point nr: 4848
Starting in MWPM state
Starting generation of point nr: 4849
Starting in MWPM state
Starting generation of point nr: 4850
Starting in MWPM state
Starting generation of point nr: 4851
Starting in MWPM state
Starting generation of point nr: 4852
Starting in MWPM state
Starting generation of point nr: 4853
Starting in MWPM state
Starting generation of point nr: 4854
Starting in MWPM state
Starting generation of point nr: 4855
Starting in MWPM state
Starting generation of point nr: 4856
Starting in MWPM state
Starting generation of p

Starting generation of point nr: 4976
Starting in MWPM state
Starting generation of point nr: 4977
Starting in MWPM state
Starting generation of point nr: 4978
Starting in MWPM state
Starting generation of point nr: 4979
Starting in MWPM state
Starting generation of point nr: 4980
Starting in MWPM state
Starting generation of point nr: 4981
Starting in MWPM state
Starting generation of point nr: 4982
Starting in MWPM state
Starting generation of point nr: 4983
Starting in MWPM state
Starting generation of point nr: 4984
Starting in MWPM state
Starting generation of point nr: 4985
Starting in MWPM state
Starting generation of point nr: 4986
Starting in MWPM state
Starting generation of point nr: 4987
Starting in MWPM state
Starting generation of point nr: 4988
Starting in MWPM state
Starting generation of point nr: 4989
Starting in MWPM state
Starting generation of point nr: 4990
Starting in MWPM state
Starting generation of point nr: 4991
Starting in MWPM state
Starting generation of p

In [11]:
iterator = MCMCDataReader(file_path, params['size'])
data = iterator.full()
for k in range(int(len(data)/2)):
    qubit_matrix = data[2*k].reshape(2,params['size'],params['size'])
    eq_distr = data[2*k+1]

    #print(qubit_matrix)
    print(eq_distr)
    print()
    #print(round(eq_distr))

[1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.90000000e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.99379588e+01 6.20309298e-02 1.02751147e-05 5.98651208e-09]

[1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.90000000e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.99977587e+01 2.23120686e-03 1.85986396e-07 9.94282199e-06]

[0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 9.90000000e+01
 2.66011938e-08 1.25262660e-03 1.05513314e-12 9.99987473e+01]

[1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.99994213e+01 1.03042091e-05 5.68393567e-04 2.01776678e-12]

[1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 9.99999900e+01 4.51999727e-19 9.99212695e-06 6.38112631e-11]

[1.00000000e+02 0.00000000e+00 0.00000000e+00 0.00000000e+00
 7.90000000e+0

200


In [4]:
import copy  # not used
import os
import sys
import time

import pickle

import numpy as np
import pandas as pd

from src.toric_model import Toric_code
from src.planar_model import Planar_code
from src.mcmc import *
from decoders import *
from src.mwpm import *


In [74]:
file_path = 'data/data_size_5_method_STDC_id_10_perror_0.05.xz'
iterator = MCMCDataReader(file_path, 5)
data = iterator.full()
klass = []
qb = []
for k in range(int(len(data)/2)):
    qubit_matrix = data[2*k].reshape(2,5,5)
    eq_distr = data[2*k+1]

    #print(qubit_matrix)
    #print(eq_distr)
    qb.append(qubit_matrix)
    klass.append(eq_distr)

In [75]:
print(len(klass))
ek = np.array(klass)


2000


In [76]:
pickle_in1 = open("defect_matrices/s5p05MWPM/few/dict.defects_stdc","rb")
pickle_in2 = open("defect_matrices/s5p05MWPM/few/dict.eq_distr_stdc","rb")

#pickle_in1 = open("defect_matrices/s5p05MWPM/few/dict.defects_1","rb")
#pickle_in2 = open("defect_matrices/s5p05MWPM/few/dict.eq_distr_1","rb")


eq_distr = []
defects = []
while 1:
    try:
        defects.append(pickle.load(pickle_in1))
        eq_distr.append(pickle.load(pickle_in2))
    except EOFError:
        break

print(len(eq_distr))
print(len(defects))

2000
2000


In [77]:
ec = np.array(eq_distr)

In [78]:
out = np.array_equal(ec,ek)
out

True

In [69]:
if len(defects)
print(defects[1])
print()
print(qb[1])
#ek[3]

(array([[0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]))

[[[0 0 0 3 0]
  [0 0 0 0 0]
  [3 0 2 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[1 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [72]:
for ix in range(len(defects)):
    if (len(np.argwhere(defects[ix][0]))+len(np.argwhere(defects[ix][1]))) == 0:
        continue
    #### REMOVE FOR REGULAR RUN, ONLY FOR FEW DEFECT SIM.
    if (len(np.argwhere(defects[ix][0]))+len(np.argwhere(defects[ix][1]))) >3:
        continue
    
    #print(defects[ix])
    #print(qb[ix])
    #print(eq_distr[ix])

(array([[0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]))
[9.99999706e+01 1.01323424e-05 1.92732282e-05 2.87961113e-12]
(array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]]))
[9.99988918e+01 5.66710042e-04 5.41507203e-04 3.00977713e-09]
(array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]]), array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]]))
[9.99999791e+01 1.06166097e-05 1.02899447e-05 2.84729392e-12]
(array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1,